baseURL = 'https://lizwkariuki58.github.io/'
languageCode = 'en-us'
title = 'Liz Kariuki'
theme = 'ublogger'

[params]
  # uBlogger theme version
  version = "2.0.X"
  defaultTheme = "dark"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

# Menu config
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link.
        title = ""
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.en.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "About Me"
        url = "/about/"
        title = ""
        weight = 4
      [[languages.en.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        post = ""
        name = ""
        url = "https://github.com/lizwkariuki58"
        title = "GitHub"
        weight = 6
      [languages.en.params]
      # site description
      description = "Liz Kariuki Blog"
      # site keywords
      keywords = ["Liz", "Wangui", "Kariuki"]
      # App icon config
      [languages.en.params.app]
        # optional site title override for the app when added to an iOS home screen or Android launcher
        title = "Liz Kariuki"
        # whether to omit favicon resource links
        noFavicon = false
        # modern SVG favicon to use in place of older style .png and .ico files
        svgFavicon = ""
        # Android browser theme color
        themeColor = "#ffffff"
        # Safari mask icon color
        iconColor = "#5bbad5"
        # Windows v8-10 tile color
        tileColor = "#da532c"
      # Search config
      [languages.en.params.search]
        enable = true
        # type of search engine ("lunr", "algolia")
        type = "algolia"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
        [languages.en.params.search.algolia]
          index = "index.en"
          appID = "PASDMWALPK"
          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      # Home page config
      [languages.en.params.home]
        # amount of RSS pages
        rss = 5
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # Gravatar Email for preferred avatar in home page
          gravatarEmail = ""
          # URL of avatar shown in home page
          avatarURL = "/images/avatar.png"
          # title shown in home page (HTML format is supported)
          title = "Liz Kariuki"
          # subtitle shown in home page (HTML format is supported)
          subtitle = "Welcome to my blog!"
          # whether to show social links
          social = true
          # disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.en.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 3
      # Social config in home page
      [languages.en.params.social]
        GitHub = "lizwkariuki58"
        Linkedin = "liz-w-kariuki"
        Telegram = "lizard_s"
        Medium = "@lizkariuki"
        Email = "lizwkariuki58@gmail.com"
        RSS = false

    # Header config
    [params.header]
      # desktop header mode ("fixed", "normal", "auto")
      # 桌面端导航栏模式 ("fixed", "normal", "auto")
      desktopMode = "fixed"
      # mobile header mode ("fixed", "normal", "auto")
      # 移动端导航栏模式 ("fixed", "normal", "auto")
      mobileMode = "auto"
      # Header title config
      # 页面头部导航栏标题配置
      [params.header.title]
        # URL of the LOGO
        # LOGO 的 URL
        logo = ""
        # title name
        # 标题名称
        name = "Liz Kariuki"
        # you can add extra information before the name (HTML format is supported), such as icons
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
        # you can add extra information after the name (HTML format is supported), such as icons
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标

        post = ""
    # Footer config
    # 页面底部信息配置
    [params.footer]
      enable = true
      # Custom content (HTML format is supported)
      # 自定义内容 (支持 HTML 格式)
      custom = ''
      # whether to show Hugo and theme info
      # 是否显示 Hugo 和主题信息
      hugo = true
      # whether to show copyright info
      # 是否显示版权信息
      copyright = true
      # whether to show the author
      # 是否显示作者
      author = true
    # Section (all posts) page config
    # Section (所有文章) 页面配置
    [params.section]
      # special amount of posts in each section page
      # section 页面每页显示文章数量
      paginate = 20
      # date format (month and day)
      # 日期格式 (月和日)
      dateFormat = "01-02"

    # List (category or tag) page config
  # List (目录或标签) 页面配置
  [params.list]
    # special amount of posts in each list page
    # list 页面每页显示文章数量
    paginate = 20
    # date format (month and day)
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # amount of RSS pages
    # RSS 文章数目
    rss = 10

  # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      HackerNews = true
  
  # Compatibility config
  # 兼容性设置
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

      # Markup related configuration in Hugo
    # Hugo 解析文档的配置
    [markup]
      # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
      # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
      [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
      # Goldmark is from Hugo 0.60 the default library used for Markdown
      # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
      [markup.goldmark]
        [markup.goldmark.extensions]
          definitionList = true
          footnote = true
          linkify = true
          strikethrough = true
          table = true
          taskList = true
          typographer = true
        [markup.goldmark.renderer]
          # whether to use HTML tags directly in the document
          # 是否在文档中直接使用 HTML 标签
          unsafe = true
      # Table Of Contents settings
      # 目录设置
      [markup.tableOfContents]
        startLevel = 2
        endLevel = 6

    # Author config
    # 作者配置
    [author]
      name = "upagge.en"

    # Sitemap config
    # 网站地图配置
    [sitemap]
      changefreq = "weekly"
      filename = "sitemap.xml"
      priority = 0.5

    # Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
    # Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)
    [Permalinks]
      # posts = ":year/:month/:filename"
      posts = ":filename"
